/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yoyojyv' at '14. 2. 17 오후 10:23' with Gradle 1.10
 *
 * @author yoyojyv, @date 14. 2. 17 오후 10:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
    	System.out.println("Hello world!");
    }
}
